# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tom/Dokumente/python/PathVisualizer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1421, 927)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(-1)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.centralwidget.setObjectName("centralwidget")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.btnStart.setObjectName("btnStart")
        self.horizontalSliderSpeed = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderSpeed.setGeometry(QtCore.QRect(180, 30, 160, 16))
        self.horizontalSliderSpeed.setMinimum(100)
        self.horizontalSliderSpeed.setMaximum(230)
        self.horizontalSliderSpeed.setSingleStep(5)
        self.horizontalSliderSpeed.setPageStep(10)
        self.horizontalSliderSpeed.setProperty("value", 100)
        self.horizontalSliderSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSpeed.setObjectName("horizontalSliderSpeed")
        self.labelSpeed = QtWidgets.QLabel(self.centralwidget)
        self.labelSpeed.setGeometry(QtCore.QRect(240, 10, 58, 16))
        self.labelSpeed.setObjectName("labelSpeed")
        self.pushButtonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(370, 10, 131, 31))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.labelColorStart = QtWidgets.QLabel(self.centralwidget)
        self.labelColorStart.setGeometry(QtCore.QRect(540, 10, 41, 16))
        self.labelColorStart.setText("")
        self.labelColorStart.setObjectName("labelColorStart")
        self.labelColorEnd = QtWidgets.QLabel(self.centralwidget)
        self.labelColorEnd.setGeometry(QtCore.QRect(540, 30, 41, 16))
        self.labelColorEnd.setText("")
        self.labelColorEnd.setObjectName("labelColorEnd")
        self.labelTextStart = QtWidgets.QLabel(self.centralwidget)
        self.labelTextStart.setGeometry(QtCore.QRect(610, 10, 71, 16))
        self.labelTextStart.setObjectName("labelTextStart")
        self.labelTextEnd = QtWidgets.QLabel(self.centralwidget)
        self.labelTextEnd.setGeometry(QtCore.QRect(610, 30, 58, 16))
        self.labelTextEnd.setObjectName("labelTextEnd")
        self.labelErklaerungWalls = QtWidgets.QLabel(self.centralwidget)
        self.labelErklaerungWalls.setGeometry(QtCore.QRect(10, 50, 571, 16))
        self.labelErklaerungWalls.setObjectName("labelErklaerungWalls")
        self.btnChangeAlgo = QtWidgets.QPushButton(self.centralwidget)
        self.btnChangeAlgo.setGeometry(QtCore.QRect(720, 10, 111, 31))
        self.btnChangeAlgo.setToolTip("")
        self.btnChangeAlgo.setToolTipDuration(1)
        self.btnChangeAlgo.setStatusTip("")
        self.btnChangeAlgo.setWhatsThis("")
        self.btnChangeAlgo.setObjectName("btnChangeAlgo")
        self.labelAlgo = QtWidgets.QLabel(self.centralwidget)
        self.labelAlgo.setGeometry(QtCore.QRect(700, 50, 261, 16))
        self.labelAlgo.setText("")
        self.labelAlgo.setObjectName("labelAlgo")
        self.btnZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.btnZoomOut.setGeometry(QtCore.QRect(900, 10, 80, 24))
        self.btnZoomOut.setObjectName("btnZoomOut")
        self.btnZoomIn = QtWidgets.QPushButton(self.centralwidget)
        self.btnZoomIn.setGeometry(QtCore.QRect(900, 40, 80, 24))
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.disclaimerLabel = QtWidgets.QLabel(self.centralwidget)
        self.disclaimerLabel.setGeometry(QtCore.QRect(1000, 10, 231, 51))
        self.disclaimerLabel.setObjectName("disclaimerLabel")
        self.btnCreateLabyrinth = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateLabyrinth.setGeometry(QtCore.QRect(1280, 10, 91, 51))
        self.btnCreateLabyrinth.setObjectName("btnCreateLabyrinth")
        self.labelState = QtWidgets.QLabel(self.centralwidget)
        self.labelState.setGeometry(QtCore.QRect(470, 60, 111, 20))
        self.labelState.setTextFormat(QtCore.Qt.RichText)
        self.labelState.setObjectName("labelState")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.labelSpeed.setText(_translate("MainWindow", "Speed"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete the Map"))
        self.labelTextStart.setText(_translate("MainWindow", "start point"))
        self.labelTextEnd.setText(_translate("MainWindow", "end point"))
        self.labelErklaerungWalls.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">draw walls: </span>press any key on your mouse</p></body></html>"))
        self.btnChangeAlgo.setText(_translate("MainWindow", "Change algorythm"))
        self.btnZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.btnZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.disclaimerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Disclaimer: </span>Zooming in or zooming</p><p>out is just allowed in Mode: Start!</p></body></html>"))
        self.btnCreateLabyrinth.setText(_translate("MainWindow", "Create a \n"
"complex \n"
"Labyrinth"))
        self.labelState.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Mode:</span><span style=\" font-weight:600; font-style:italic;\"> Start</span></p></body></html>"))

